name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build the Docker image
      - name: Build the Docker image
        run: docker build -t binomial-theorem .

      # Run the Docker container
      - name: Run the Docker container
        run: docker run --rm binomial-theorem
