name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write  # Required to push to GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}  

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/binomial-theorem:latest .

      - name: Push the image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/binomial-theorem:latest
