name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code,
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      # Setup Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Build Docker image
      - name: Build Docker image
        run: docker build -t binomial-theorem .

      # Run Docker container
      - name: Run Docker container
        run: docker run --rm binomial-theorem

      # Push image to registry
      - name: Push image to registry
        run: |
          docker tag binomial-theorem ghcr.io/${{ github.repository_owner }}/binomial-theorem:latest
          docker push ghcr.io/${{ github.repository_owner }}/binomial-theorem:latest
